export const POST_GET_LIST_REQUEST = "POST_GET_LIST_REQUEST";
export const POST_GET_LIST_SUCCESS = "POST_GET_LIST_SUCCESS";
export const POST_GET_LIST_FAIL = "POST_GET_LIST_FAIL";
export const POST_GET_LIST_RESET = "POST_GET_LIST_RESET";
export const POST_LIST_UPDATE_ADD_POST = "POST_LIST_UPDATE_ADD_POST";
export const POST_LIST_UPDATE_DELETE_POST = "POST_LIST_UPDATE_DELETE_POST";


export const POST_CREATE_REQUEST = "POST_CREATE_REQUEST";
export const POST_CREATE_SUCCESS = "POST_CREATE_SUCCESS";
export const POST_CREATE_FAIL = "POST_CREATE_FAIL";
export const POST_CREATE_RESET = "POST_CREATE_RESET";


export const POST_REMOVE_REQUEST = "POST_REMOVE_REQUEST";
export const POST_REMOVE_SUCCESS = "POST_REMOVE_SUCCESS";
export const POST_REMOVE_FAIL = "POST_REMOVE_FAIL";
export const POST_REMOVE_RESET = "POST_REMOVE_RESET";